### PR TITLE
Fix a crash when comparing differently sized images

### LINKED ISSUE #14: Image.getPixel called with out of bounds coordinates
When using `SimpleImageComparator` with a vshift/hshift, it's possible for Differ to call `Image.getPixel` with out of bounds values if the images have different sizes.

The issue is on line 51 of `ImageComparator`, there is a range check but it checks `x` and `y`, not `offsetX` and `offsetY`

### PR DESCRIPTION
**Pull request by ansman**
This fixes #14

### CODE REVIEW

File: differ/src/commonTest/kotlin/com/dropbox/differ/ShiftComparisonTest.kt [hunk 1]
```diff
@@ -61,4 +61,14 @@ class ShiftComparisonTest {
     assertEquals(comparator.hShift, 0)
     assertEquals(comparator.vShift, 10)
   }
+
+  @Test fun `returns DIFFERENT for different sized images`() {
+    val first = TestImage(width = 1080, height = 1080)
+    val second = TestImage(width = 1080, height = 540)
+    second.setPixel(second.width - 1, second.height - 1, Color(0f, 0f, 0f, 0f))
```
Comment (ansman) [inline differ/src/commonTest/kotlin/com/dropbox/differ/ShiftComparisonTest.kt:68]: We need at least one pixel to differ for the shift code to run.
